version: "3.8"
services:
  broker:
    container_name: broker
    image: "sriggi/caesar-rest-broker"
    ports:
      - "5672:5672"
    command: rabbitmq-server
    restart: always
  db:
    container_name: db
    image: "sriggi/caesar-rest-db"
    ports:
      - "27017:27017"
    command: mongod
    restart: always
  app:
    container_name: app
    depends_on:
      - broker
      - db
    image: "sriggi/caesar-rest"
    ports:
      - "3031:3031"
    environment:
      - PORT=3031
      - NWORKERS=2
      - NTHREADS=2
      - DBHOST=db
      - DBPORT=27017
      - DBNAME=caesardb
#     - SECRETFILE=/etc/systemd/system/client_secrets.json
      - AAI=0
      - BROKER_URL=amqp://guest:guest@broker:5672/
      - BROKER_HOST=broker
      - BROKER_PORT=5672
      - BROKER_PROTO=amqp
      - BROKER_USER=guest
      - BROKER_PASS=guest
      - RESULT_BACKEND_URL=mongodb://db:27017/caesardb
      - RESULT_BACKEND_HOST=db
      - RESULT_BACKEND_PORT=27017
      - RESULT_BACKEND_PROTO=mongodb
      - RESULT_BACKEND_DBNAME=caesardb
    volumes:
      - /opt/caesar-rest/data:/opt/caesar-rest/data
      - /opt/caesar-rest/jobs:/opt/caesar-rest/jobs
    restart: always
  worker:
    container_name: worker
    depends_on:
      - broker
      - db
      - app
    image: "sriggi/caesar-rest-worker"
    environment:
      - NPROC=2
      - BROKER_URL=amqp://guest:guest@broker:5672/
      - BROKER_HOST=broker
      - BROKER_PORT=5672
      - BROKER_PROTO=amqp
      - BROKER_USER=guest
      - BROKER_PASS=guest
      - RESULT_BACKEND_URL=mongodb://db:27017/caesardb
      - RESULT_BACKEND_HOST=db
      - RESULT_BACKEND_PORT=27017
      - RESULT_BACKEND_PROTO=mongodb
      - RESULT_BACKEND_DBNAME=caesardb
    volumes:
      - /opt/caesar-rest/data:/opt/caesar-rest/data
      - /opt/caesar-rest/jobs:/opt/caesar-rest/jobs
    restart: always
  load_balancer:
    container_name: load_balancer
    depends_on:
      - app
    image: "sriggi/caesar-rest-lb"
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      SERVERS: app:3031
    restart: always  

